# The Python way

In [12]:
values = [1,2,3,4,5]
print(values)
for i in range(len(values)):
    values[i] += 5
print(values)
print(type(values))

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
<class 'list'>


# The NumPy way

In [26]:
import numpy as np
values = [1,2,3,4,5]
print(values)
print(type(values))
values = np.array(values) + 5
print(values)
print(type(values))

[1, 2, 3, 4, 5]
<class 'list'>
[ 6  7  8  9 10]
<class 'numpy.ndarray'>


In [20]:
values += 5
print(values)
print(type(values))

[11 12 13 14 15]
<class 'numpy.ndarray'>


We should point out, NumPy actually has functions for things like adding, multiplying, etc. But it also supports using the standard math operators. So the following two lines are equivalent:

In [21]:
some_array = [1,2,3,4,5]
x = np.multiply(some_array, 5)
print(x)
print(type(x))
x = some_array * 5
print(x)
print(type(x))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
<class 'list'>


One more example of operating with scalars and ndarrays. Let's say you have a matrix m and you want to reuse it, but first you need to set all its values to zero. Easy, just multiply by zero and assign the result back to the matrix, like this:

In [28]:
m = np.array([[1],[2,3,4,5]])
print(m)
print(type(m))
m *= 0
print(m)
print(type(m))
# now every element in m is zero, no matter how many dimensions it has

[[1] [2, 3, 4, 5]]
<class 'numpy.ndarray'>
[[] []]
<class 'numpy.ndarray'>


# Here's the example from the video:

In [29]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [30]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [31]:
a + b

array([[ 3,  7],
       [11, 15]])

# And if you try working with incompatible shapes, like the other example from the video, you'd get an error:

In [32]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [33]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [34]:
a.shape

(2, 2)

In [35]:
c.shape

(3, 3)

In [36]:
a + b
#it gives no error but not a good addition.

array([[ 3,  7],
       [11, 15]])