# Element-wise Multiplication

In [1]:
import numpy as np

In [2]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [5]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [6]:
np.multiply(m, n)   # equivalent to m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

# Matrix Product
To find the matrix product, you use NumPy's matmul function.

If your have compatible shapes, the it's as simple as this:

In [7]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a.shape

(2, 4)

In [9]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
b.shape

(4, 3)

In [11]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [12]:
c.shape

(2, 3)

If your matrices have incompatible shapes, you'll get an error, like the following:

In [13]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

# NumPy's dot function
You may sometimes see NumPy's dot function in places where you would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.

So these two results are equivalent:

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [16]:
a.dot(a)  # you can call `dot` directly on the `ndarray`

array([[ 7, 10],
       [15, 22]])

In [17]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])