# Implementing the hidden layer

Programming quiz
Below, you'll implement a forward pass through a 4x3x2 network, with sigmoid activation functions for both layers.

Things to do:

    Calculate the input to the hidden layer.
    Calculate the hidden layer output.
    Calculate the input to the output layer.
    Calculate the output of the network.

Remember how the input to a hidden unit is the sum of all the inputs multiplied by the hidden unit's weights.

In [191]:
import numpy as np

# Defining the sigmoid function for activations
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4 # number of input layers
N_hidden = 3 # number of hidden layers
N_output = 2 # number of output layers
bias = -1.0

# This method is called when RandomState is initialized. It can be called again to re-seed the generator. 
# For details, see RandomState.
np.random.seed(42)

# Make some fake data ”inputs”. Return a sample (or samples) from the “standard normal” distribution.
X = np.random.randn(4)
print("Make some fake data ”inputs”. Return a sample (or samples) from the “standard normal” distribution.")
print(X, type(X), np.shape(X))

# initialize hidden weights providing the shape of the matrix with 
# the number of input layers and number of hidden layers
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
print("Initialize hidden weights")
print(weights_input_to_hidden, type(weights_input_to_hidden), np.shape(weights_input_to_hidden))

# initialize output weights providing the shape of the matrix with 
# the number of hidden layers and number of output layers
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
print("Initialize output weights")
print(weights_hidden_to_output, type(weights_hidden_to_output), np.shape(weights_hidden_to_output))

# TODO: Make a forward pass through the network


# The linear combination of the inputs * random hidden_weights + bias form the input h.
hidden_layer_in = bias+(np.dot(X, weights_input_to_hidden))
print("The linear combination of the inputs * random hidden_weights + bias form the input h.")
print(hidden_layer_in)

# h passes through the activation function giving the final output of the perceptron, labeled y. 
# Hidden-layer Output using np.dot (y-hat)
hidden_layer_out = sigmoid(hidden_layer_in)
print("Hidden-layer Output using np.dot")
print('Hidden-layer Output:')
print(hidden_layer_out)

# The linear combination of the hidden_layer inputs * random output_weights + bias form the input h.
output_layer_in = bias+(np.dot(hidden_layer_out, weights_hidden_to_output))
print("The linear combination of the hidden_layer inputs * random output_weights + bias form the input h.")
print(output_layer_in)

# h passes through the activation function giving the final output of the perceptron, labeled y. 
# Hidden-layer Output using np.dot (y-hat)
output_layer_out = sigmoid(output_layer_in)
print("Hidden-layer Output using np.dot")
print('Output-layer Output:')
print(output_layer_out)

Make some fake data ”inputs”. Return a sample (or samples) from the “standard normal” distribution.
[ 0.49671415 -0.1382643   0.64768854  1.52302986] <class 'numpy.ndarray'> (4,)
Initialize hidden weights
[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]] <class 'numpy.ndarray'> (4, 3)
Initialize output weights
[[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]] <class 'numpy.ndarray'> (3, 2)
The linear combination of the inputs * random hidden_weights + bias form the input h.
[-1.34365494 -1.29801368 -0.99902638]
Hidden-layer Output using np.dot
Hidden-layer Output:
[ 0.20690965  0.2144995   0.26913289]
The linear combination of the hidden_layer inputs * random output_weights + bias form the input h.
[-1.0009881  -1.02986815]
Hidden-layer Output using np.dot
Output-layer Output:
[ 0.26874719  0.26310967]


In [91]:
import numpy as np
test1 = np.array([[[0,0],[1,1]],
                 [[2,2],[3,3]]])
print(test1, type(test1), np.shape(test1))

mu, sigma = 0, 0.1 # mean and standard deviation
print(mu, type(mu), np.shape(mu))
print(sigma, type(sigma), np.shape(sigma))

#s = np.random.normal(mu, sigma, 1000)
s1 = np.random.normal(mu, sigma, size=(2,2))
s2 = np.random.normal(size=(3,3))
s3 = np.random.normal() 
s4 = np.random.randn(2, 2)
s5 = np.random.randn(4)

#print(s, type(s), np.shape(s))
print(s1, type(s1), np.shape(s1))
print(s2, type(s2), np.shape(s2))
print(s3, type(s3), np.shape(s3))
print(s4, type(s4), np.shape(s4))
print(s5, type(s5), np.shape(s5))

np.random.seed(42)

#weights_input_to_hidden = np.random.normal(0, n_inputs**-0.5, size=(n_inputs, n_hidden))
#hidden_inputs = np.dot(inputs, weights_input_to_hidden)

[[[0 0]
  [1 1]]

 [[2 2]
  [3 3]]] <class 'numpy.ndarray'> (2, 2, 2)
0 <class 'int'> ()
0.1 <class 'float'> ()
[[ 0.04967142 -0.01382643]
 [ 0.06476885  0.15230299]] <class 'numpy.ndarray'> (2, 2)
[[-0.23415337 -0.23413696  1.57921282]
 [ 0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227]] <class 'numpy.ndarray'> (3, 3)
-1.913280244657798 <class 'float'> ()
[[-1.72491783 -0.56228753]
 [-1.01283112  0.31424733]] <class 'numpy.ndarray'> (2, 2)
[-0.90802408 -1.4123037   1.46564877 -0.2257763 ] <class 'numpy.ndarray'> (4,)


In [92]:
import numpy as np
from data_prep import features, targets, features_test, targets_test


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

# TODO: We haven't provided the sigmoid_prime function like we did in
#       the previous lesson to encourage you to come up with a more
#       efficient solution. If you need a hint, check out the comments
#       in solution.py from the previous lecture.

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))


# Use to same seed to make debugging easier
np.random.seed(42)

# Number of records and input units
n_records, n_features = features.shape
print(features.shape)
print(n_records, n_features)
print(type(features))
print(features.head(10))
last_loss = None

# Number of hidden units
n_hidden = 2
#weights_input_to_hidden = np.random.normal(0, n_inputs**-0.5, size=(n_inputs, n_hidden))

# Initialize weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)
print(weights)

# Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

for e in range(epochs):
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Loop through all records, x is the input, y is the target

        # Note: We haven't included the h variable from the previous
        #       lesson. You can add it if you want, or you can calculate
        #       the h together with the output

        # TODO: Calculate the output
        output = np.dot(x, weights)

        # TODO: Calculate the error
        error = y - sigmoid(output)

        # TODO: Calculate the error term
        error_term = error * sigmoid_prime(output)

        # TODO: Calculate the change in weights for this sample
        #       and add it to the total weight change
        del_w += error_term * x

    # TODO: Update weights using the learning rate and the average change in weights
    weights += learnrate * del_w / n_records

    # TODO: Update weights using the learning rate and the average change in weights
    weights += 0

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss


# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

(360, 6)
360 6
<class 'pandas.core.frame.DataFrame'>
          gre       gpa  rank_1  rank_2  rank_3  rank_4
209 -0.066657  0.289305       0       1       0       0
280  0.625884  1.445476       0       1       0       0
33   1.837832  1.603135       0       0       1       0
210  1.318426 -0.131120       0       0       0       1
93  -0.066657 -1.208461       0       1       0       0
84  -0.759199  0.552071       0       0       1       0
329 -0.759199 -1.208461       0       0       0       1
94   0.625884  0.131646       0       1       0       0
266 -0.239793 -0.393886       0       0       0       1
126  0.106478  0.394412       1       0       0       0
[ 0.2027827  -0.05644616  0.26441774  0.62177434 -0.09559271 -0.09558601]
Train loss:  0.2627609385
Train loss:  0.209286194093
Train loss:  0.200842929081
Train loss:  0.198621564755
Train loss:  0.197798513967
Train loss:  0.197425779122
Train loss:  0.197235077462
Train loss:  0.197129456251
Train loss:  0.197067663413
Train l

In [ ]:
a = 3
b = 13

print (a)

def hidden_layer_in1(X, w):
    
    if X==3:
        print ("test")
        print (X)
        X = 0
        a = 0 
        print (X)
        #return = np.dot(X,weights_input_to_hidden)
        return X
    elif w==13:
        w = 15
        return w
    
mira = hidden_layer_in1(a, b)
print (a)
print (mira)

mira2 = hidden_layer_in1(a, b)
print (hidden_layer_in1(a, b))